### ISSUE TITLE
Babel just broke `estree-to-babel`

### ISSUE THREAD

**Issue by wooorm** [coderaiser/estree-to-babel#1]
This project uses `@babel/types` to check for certain estree types, which just broke today.

E.g.,:

https://github.com/coderaiser/estree-to-babel/blob/be2fbd97444bf840992923624500645b8f9117e7/lib/estree-to-babel.js#L27-L28

`estree` literals have a `type` set to `Literal`, babel nodes don’t.

This non-babel type was previously supported: https://github.com/babel/babel/blame/c0a8cbd9890182b05d398c422178d3552ee7f75d/packages/babel-types/src/validators/generated/index.ts#L4097

But this was removes a couple days ago, which was released in the last 24 hours: https://github.com/babel/babel/blame/bfb51362c76f3fd635587ebab34cc369be5f9289/packages/babel-types/src/validators/generated/index.ts#L4742

The same problem might be true for `isObjectExpression` 🤔

**Comment by coderaiser** [comment]
Landed in [v3.0.1](https://github.com/coderaiser/estree-to-babel/releases/tag/v3.0.1) 🎉

**Comment by wooorm** [comment]
Sweeet, thanks for landing @coderaiser!
