### ISSUE TITLE
Add support for comments

### ISSUE THREAD

**Issue by wooorm** [coderaiser/estree-to-babel#3]
Some estree parsers support comments.
Babel does too.
It would be nice to handle comments in estrees and add them to Babel trees too.

There are two ways to do comments.

- Comment attachment (fields on nodes, `leadingComments`, `trailingComments`, `innerComments`)
- Comment list (`comments` field on the program node with all comments)

Comment attachment is rather complex, espree recently removed it.

Here’s a breakdown of what I could find on astexplorer:

| Parser | Estree | Comment attachment | Comment list |
| - | - | - | - |
| `acorn` | yes | | with a couple lines of code |
| `@babel/eslint-parser` | yes | yes | yes |
| `@babel/parser` | | yes | yes |
| `espree` | yes | not anymore | yes |
| `esprima` | yes | yes | yes |
| `miriyah` | yes | | |
| `recast` | yes | sort of | |
| `traceur` | | | sort of |
| `recast` | yes | sort of | |
| `@typescript-eslint/parser` | yes | | yes |

It would be great if either attached comments could also make their way to Babel (transformed, because estree uses `Block` and `Line` types and Babel uses `BlockComment` and `LineComment`),
and it would be marvelous if an estree’s root `comments` array could also be attached to Babel nodes.

**Comment by wooorm** [comment]
I guess changing an estree `comment` array to attached comments might be useful in just estree land, as a separate package. Which might be useful here too

**Comment by coderaiser** [comment]
This is a very good idea for a Pull Request :).

**Comment by wooorm** [comment]
The algorithm for attaching comments I mentioned above does seem to be implemented somewhere already: https://github.com/davidbonnet/astravel#astravelattachcommentsast-comments--ast
