### ISSUE TITLE
Issue converting to RegExpLiteral

### ISSUE THREAD

**Issue by beauroberts** [coderaiser/estree-to-babel#5]
Hello! Thanks for creating and maintaining an awesome tool. I'm using it to pipe `react-docgen` generated AST into `@babel/generate`. In doing so, I came across an issue where regex literals were not being properly translated. It looks like in [`estree` the `pattern` and `flags` values are stored in a `regex` property on the `Literal` node](https://astexplorer.net/#/gist/153ea10c7eccff7e1a5e6b166b6cf575/ceafca17418fc60e71809396298a2bb6b39f77dd), whereas in [`@babel/parser` these values are stored directly on the `RegExpLiteral` node](https://astexplorer.net/#/gist/cac9f4f31518044a13cb2880224c4f04/f2d384a6f13d24582b671104cd2e193ac3c411da).

I'll submit a PR shortly with what I think is a fix.

Thank you!

**Comment by coderaiser** [comment]
Thanks a lot :), landed in [v3.1.1](https://github.com/coderaiser/estree-to-babel/releases/tag/v3.1.1) 🎉
