### ISSUE TITLE
Support Node 12 too

### ISSUE THREAD

**Issue by wooorm** [coderaiser/estree-to-babel#7]
heya! 👋

Node 12 doesn’t support `node.extra?.raw`, but it does support ESM: could I convince you to support Node 12 too?

**Comment by coderaiser** [comment]
Feel free to make PR :)

**Comment by wooorm** [comment]
What was the reason for dropping 12 too btw? It's still maintained. Node 10 is EOL end of this month, but v12 will remain for a while

**Comment by coderaiser** [comment]
Using `optional chaining` and simplifying, standardizing support of all projects I’m working on. Maybe you will need to disable one of `putout` rules called: `apply-optional-chaining`.

What purpose of using node `v12` If `node v16` will be released soon, and it will be LTS in half of a year? Sooner community drops old versions, faster new simpler and better constructions (like `replaceAll` from node v15) will came to life.

Here is [release schedule](https://nodejs.org/en/about/releases/), I think supporting two latest versions of node should be enough, but you can try to convince me.

**Comment by wooorm** [comment]
[responded in the pr](https://github.com/coderaiser/estree-to-babel/pull/8#issuecomment-822251372)!

**Comment by coderaiser** [comment]
I see no reason to wait for a year, while some folks will update their infrastructure, `v3` will be maintained if it will have sense. I close it for now, you didn't convince me.
